### ISSUE TITLE
rosserial

### ISSUE THREAD

**Issue by floriantschopp** [ethz-asl/eth_supermegabot#2]
For the battery monitor, the rosserial package would be required (https://github.com/ros-drivers/rosserial/).
Please add this to the ws_tools.

To connect to the arduino, one needs the command:
```
rosrun rosserial_python serial_node.py _port:=/dev/ttyUSB0 _baud:=250000
```

**Comment by hermannsblum** [comment]
@floriantschopp `rosserial` is in the dependencies, can we close this issue?
