### ISSUE TITLE
Missing dependency in detector

### ISSUE THREAD

**Issue by KH-Kyle** [ethz-asl/eth_supermegabot#36]
In the `detector` packages, where the `yaml_tools` package is used the following should be added to the package.xml:

<depend>yaml_tools</depend>
This should solve any linking issues relating to the `yaml_tools` packages that sometimes occur when using catkin build.

**Comment by hermannsblum** [comment]
hey @KH-Kyle, Thanks for documentng all of this!
ideally you can already open PullRequests for those issues where you found a solution.
